### PR TITLE
- Added perceived brightness correction, by using the inverted  CIE 1…

### PR DESCRIPTION
**Pull request by thijse**
Hi,

Thanks for the nice library! I made some modifications I hope you would like to merge:
- Added perceived brightness correction, by using the inverted  CIE 1931 mapping from XYZ color space to Lab space. If you'd like I can give you the code for the C# program I made to calculate it. I added the ability to turn this on/off through the constructor
- Speed optimization. The fade-in/fade-out update() calls used to take +/- 120us, but with some minor optimizations I got it down to +/- 45 us. This is largely through the precalculation of values, making the elapsedTime-to-brightness calculation a lot faster. 

There are a lot of 1-line functions in your code, that make the code very ledgable, but I feared it would give a performance penalty. I forced inlining for 
a) small, private functions 
b) larger, private functions that are called only once

Honestly, this only makes a small difference (1-2 us). 

Another interesting finding: removing the constrain function (which is not needed anymore, since I use uint8_t values) actually SLOWS the update() function with 10us.
- Added upper and lower values for the brightness intensity for the fade and blink loops.

### CODE REVIEW

**Comment by alextaujenis** [comment]
Just to wrap my head around this...
"Our perception of changes in luminance isn't linear, which means linear increments of additional light doesn't mean linear increments of our perception of the brightness of light." - [source](http://ninedegreesbelow.com/photography/xyz-rgb.html#TRCs)

Here is a graph of your proposed luminance curve along with the line for how the library currently increases the brightness of a light. Can you post the C# source for calculating the curve from the CIE 1931 XYZ space?

[graph](https://jsfiddle.net/gvz4Lu7m/)

**Comment by thijse** [comment]
That's precisely it! I won't claim to be an expert in color spaces, but what I did is look at how the
XYZ space is mapped to the Lab space, and in particular to [Luminance](https://en.wikipedia.org/wiki/CIE_1931_color_space) (Y/Yn) to [Lighness](https://en.wikipedia.org/wiki/Lab_color_space) (L). The Lab standard is defined to be perceived as a linear scale by the human eye, so we want the led intensity walk the L scale with fixed stepsize, and map this to Y/Yn, (which, in turn, scales linearly with the PMW signal). This means we need to calculate the inverse of the Y/Yn-> Lab mapping (see the link to the [L\* Companding equations](http://www.brucelindbloom.com/index.html?Eqn_XYZ_to_RGB.html) in the source that you recite).

After this I map to the 8-bit output value (for the PWM pin). I tried using a 16-bit input value, but did not give a smoother transition than the 8-bit input. I assumed that a lookup table would be faster than realtime calculation, but I am now thinking I can optimize realtime calculation quite a bit by pre-calculating parts.

Please find attached [LookupTableGenerator.zip](https://github.com/alextaujenis/RBD_Light/files/289283/LookupTableGenerator.zip)
which holds the lookup generator, and the Excel sheet that shows the calculated values. These seem to match the graph you show very nicely.

image

**Comment by alextaujenis** [comment]
In your lookup table generator:

``` cs
if (L > 7.9996248) 
{
  Y = Math.Pow((L+16),3)/116;
}
else
{
  Y = L/(903.3);
}
```

How did you calculate **7.9996248** from Y/Yn > 0.008856?

**Comment by thijse** [comment]
I wanted to write: simply by filling in `L_threshold (=0.008856)` in either formula should yield `Y_threshold(=7.9996248)`. However, when I tried it out, only the linear formula gave this value. Looking at it, I discovered I made a very dumb mistake in inverting the power formula:

`Y = Math.Pow((L+16),3)/116`

should obviously be

`Y = Math.Pow((L + 16), 3)/Math.Pow(116, 3)`

The difference is quite subtle, and is only seen in the lower end of the curve (see zoomed-in graph), But it still matters, since the eye is most sensitive there.
image
Funnily enough, I was not satisfied with the lookup table, so for your library I had already manually tuned for the lower end values in a way that turns out to be neary consistent with the outcomes of the fixed formula )

**Comment by alextaujenis** [comment]
@thijse I have a background in human-computer interaction so I think this concept is really cool, however I would be hesitant to add this to the library without being able to fully reproduce the curve. I will also want to translate the equation into javascript so I can show the curve in the docs (without using the lookup table).

I can speak in C++, C#, Ruby, JavaScript, or whatever language you'd like, but I'd like the calculation to be known. Here is my attempt to understand this transformation with Ruby

``` ruby
# L* = 116(Y/Yn)^1/3 - 16 , Y/Yn > 0.008856
# L* = 903.3(Y/Yn)        , Y/Yn <= 0.008856

min = 0
max = 255

values = (min..max).each.map do |i|
  percent = i / max.to_f
  l = percent * 100

  if percent > 0.008856
    ((l + 16) ** 3) / (116 ** 3)
  else
    l / 903.3
  end
end

largest = values.max

output = values.each.map do |value|
  (value * max / largest * 2).round / 2
end

puts output.to_s
```

Which produces this curve (click it to compare to yours):
[screen shot 2016-06-01 at 2 18 25 pm](https://jsfiddle.net/4w1op6o7/)

From what I can tell: the arc of the curve is identical but it differs slightly in the lower end, and also from different types of rounding.

I'm not an expert in this field so I'm not sure about the correct solution. Can you re-write your c# implementation with more confidence and without hand-tuning?

**Comment by thijse** [comment]
I fully understand that you want to really understand this mapping before implementing it.
 I looked at your JavaScript implementation, and I've found an issue with it:

 your line 
    `if percent > 0.008856`

 should be
    `if l > 7.9996248`

 The reason is that on the horizontal axis we do not plot `Y/Yn`, and as such the transition point should not be `Y/Yn_tresh = 0.008856`. Instead, on our horizontal axis we plot `L*`, and therefore we should use the transition point `L*_thresh`. This point we can derive from `Y/Yn_tresh`, by filling in

 `L*_thresh =  116((Y/Yn)_thresh)^1/3 - 16 = 116(0.008856)^1/3 - 16 = 7.9996248`
 or 
`L*_thresh = 903.3*(Y/Yn)_thresh          = 903.3 * 0.008856       = 7.9996248`

 I now use the same rounding in my C# code as you use in your Python implementation, so if you include the fix above, I believe we will come to the same values

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Windows.Forms;

namespace LookupTableGenerator
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void GenerateLookupButtonClick(object sender, EventArgs e)
        {
            EvaluateExpression();
        }

        private void EvaluateExpression()
        {
            // Use these parameters for configuration
            var maxL              = 255;
            var minL              = 0  ;
            var maxY              = 255;

            var stepsize          = 1  ;
            var itemsPerLine      = 10 ;

            var blockPrefix       = "const uint8_t pwm_table[] PROGMEM = {";
            var blockPostfix      = "};";
            var linePrefix        = "  ";
            var linePostfix       = ",";

            // The settings above give the following lookup table

            // const uint8_t pwm_table[] PROGMEM = {
            //      0,   0,   0,   0,   0,   1,   1,   1,   1,   1,
            //      1,   1,   1,   1,   2,   2,   2,   2,   2,   2,
            //      2,   2,   2,   3,   3,   3,   3,   3,   3,   3,
            //      3,   4,   4,   4,   4,   4,   4,   5,   5,   5,
            //      5,   5,   6,   6,   6,   6,   6,   7,   7,   7,
            //      7,   8,   8,   8,   8,   9,   9,   9,  10,  10,
            //     10,  10,  11,  11,  11,  12,  12,  12,  13,  13,
            //     13,  14,  14,  15,  15,  15,  16,  16,  17,  17,
            //     17,  18,  18,  19,  19,  20,  20,  21,  21,  22,
            //     22,  23,  23,  24,  24,  25,  25,  26,  26,  27,
            //     28,  28,  29,  29,  30,  31,  31,  32,  32,  33,
            //     34,  34,  35,  36,  37,  37,  38,  39,  39,  40,
            //     41,  42,  43,  43,  44,  45,  46,  47,  47,  48,
            //     49,  50,  51,  52,  53,  54,  54,  55,  56,  57,
            //     58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
            //     68,  70,  71,  72,  73,  74,  75,  76,  77,  79,
            //     80,  81,  82,  83,  85,  86,  87,  88,  90,  91,
            //     92,  94,  95,  96,  98,  99, 100, 102, 103, 105,
            //    106, 108, 109, 110, 112, 113, 115, 116, 118, 120,
            //    121, 123, 124, 126, 128, 129, 131, 132, 134, 136,
            //    138, 139, 141, 143, 145, 146, 148, 150, 152, 154,
            //    155, 157, 159, 161, 163, 165, 167, 169, 171, 173,
            //    175, 177, 179, 181, 183, 185, 187, 189, 191, 193,
            //    196, 198, 200, 202, 204, 207, 209, 211, 214, 216,
            //    218, 220, 223, 225, 228, 230, 232, 235, 237, 240,
            //    242, 245, 247, 250, 252, 255,
            // };

            var lookupFilePath    = @"lookup.txt";

            // Work starts here
            var items             = 0;
            var lines             = new List<string>();
            var line              = "";
            var valueList         = new List<double>();
            var scaleX            = 100.0/(double)maxL;             // ScaleX makes x run from 0..100


            var Ymax = double.MinValue; // Calculate maximum value of L to scale to the output range later on
            for (var i = minL; i <= maxL; i+=stepsize)
            {
                // ScaleX makes L run from 0..100
                var L = scaleX*(double)i;

                // We want to calculate the inverse of 

                // L* = 116(Y/Yn)^1/3 - 16          , when  Y/Yn >  0.008856   
                // L* =                             , when  Y/Yn <= 0.008856

                // That is

                // Y/Yn = ((L* + 16) / 116)^3       , when  L*_thresh >  116((Y/Yn)_thresh)^1/3 - 16 = 116(0.008856)^1/3 - 16 = 7.9996248
                // Y/Yn = L* / 90903.3(Y/Yn)3.3     , when  L*_thresh <= 903.3*(Y/Yn)_thresh         = 903.3 * 0.008856       = 7.9996248

                double Y;
                if (L > 7.9996248) 
                {
                    Y = Math.Pow((L + 16.0), 3)/Math.Pow(116.0, 3);
                }
                else
                {
                    Y = L/(903.3);
                }
                Ymax = Math.Max(Ymax, Y); // Calculate maximum value of L to scale to the output range later on
                valueList.Add(Y);
            }
            // scale to the output range to maxY
            var yscale = maxY/Ymax;

            // Write to file with some formattting
            lines.Add(blockPrefix);
            foreach (var value in valueList)
            {
                // Round floating point value to Uint
                uint scaledY = Convert.ToUInt16(value*yscale);
                if (itemsPerLine == 1)
                {
                    line = linePrefix + string.Format("{0,4}", scaledY) + linePostfix;
                    lines.Add(line);
                }
                else
                {
                    if (items == 0)
                    {
                        line = linePrefix + string.Format("{0,4}", scaledY);
                        items++;
                    }
                    else if (items < itemsPerLine - 1)
                    {
                        line = line + "," + string.Format("{0,4}", scaledY);
                        items++;
                    }
                    else
                    {
                        // add prefix
                        line = line + "," + String.Format("{0,4}", scaledY) + linePostfix;
                        lines.Add(line);
                        line = "";
                        items = 0;
                    }
                }
            }
            if (!string.IsNullOrEmpty(line)) lines.Add(line + linePostfix);
            lines.Add(blockPostfix);

            File.WriteAllLines(lookupFilePath, lines);

        }
    }
}
```

Find attacked the lookup table generated
[LookupTableGenerator.zip](https://github.com/alextaujenis/RBD_Light/files/296354/LookupTableGenerator.zip)

and the below the Arduino code:
[RBD_Light.zip](https://github.com/alextaujenis/RBD_Light/files/296366/RBD_Light.zip)

No manual tuning was done!

**Comment by thijse** [comment]
Hi,

Did you have time to look at my explanation. Also, I updated the lookup table and added it to the pull request, together with a bugfix..

**Comment by alextaujenis** [comment]
Hi @thijse,

I appreciate the work you have put into this PR, however I'm not going to merge it at this time. I believe perceived brightness correction would be a great addition to this library, but my concern right now is how bloated this library is for just fading and blinking lights.

In the near future this library will be completely re-written, but will still adhere to the documented public API. I will revisit perceived brightness correction at that time.

**Pull request closed without merging**
